[mypy]
python_version = 3.10
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
explicit_package_bases = True
namespace_packages = True
no_implicit_optional = False
check_untyped_defs = False
disable_error_code = var-annotated,has-type,no-any-return,import-untyped

# Exclude virtual environment and cache directories
exclude = (?x)(
    ^\.venv/
    | ^\.mypy_cache/
    | ^__pycache__/
  )
